[package]
name = "my-app"
version = "0.1.0"
edition = "2024"
description = "My app Rust implementation."
license = "MIT"
authors = ["Data Workspace Template"]

[dependencies]

[lints]
workspace = true
